name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الكود
        uses: actions/checkout@v4

      - name: خطوة تجريبية
        run: echo "Hello from CI"
